[package]
name = "querier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.5.0" }
models = { path = "../models" }
schemars = "0.8.15"
serde = { version = "1.0.189", default-features = false, features = ["derive"] }
